### ISSUE TITLE
Sort names as per the contributions

### ISSUE THREAD

**Issue by tapaswenipathak** [tapasweni-pathak/Women-GitHubers#46]
Women started adding their names in the repository. I support self nominations, if adding their name here, encourages them. But to keep the purpose of this repository alive, I'll be sorting the names based on the following criteria 
- Number of Repositories (One should own the source code)
- Contributions made to other projects
- Last Active
- Longest GitHub streak
- Top 3 most starred repositories
- Number of followers

I can add more criteria if needed.

The new readme will have a table having all these information in separate columns. 

As this is a time consuming task, I would be happy to have pull request fixing this issue. I'll study them before merging. Keep your names coming. :)

**Comment by sara-02** [comment]
You can specify a score for each of this criteria, they will act like weights, and give you a final score.

**Comment by musicakc** [comment]
Make a table and then write a python script based on that table for the weighted score @sara-02? Can be done pretty easily.

**Comment by thefourtheye** [comment]
That kinda beats the purpose I guess. When you sort, there is always someone who has to end up at the last position. I don't want to see that. I thought that the purpose of this repo is to encourage people.

Moreover many people may not be able to regularly contribute because of their work schedule, family and there could be so many other reasons. Apart from that quality matters over quantity.

These are just my opinions.

**Comment by PrabhanshuAttri** [comment]
Hey @tapasweni-pathak 
I think a graphic page with some interactiveness will be better than a table. We tried doing it. https://women-on-github.herokuapp.com/
It still needs improvements. I am working on it
